### ISSUE TITLE
Error Execute

### ISSUE THREAD

**Issue by edy-dev** [TheMrinalSinha/allitebooks.com#1]
C:\GitHub\allitebooks.com>python --version
Python 3.8.2

C:\GitHub\allitebooks.com>python allitebooks.py
allitebooks.py:56: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if name is ('title'): return (header_details.xpath('./h1/text()') or [''])[0]
allitebooks.py:57: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if name is ('dlink'): return (book.xpath('//span[@class="download-links"]/a[contains\
allitebooks.py:59: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if name is ('cover'): return (header_details.xpath('.//div/a/img/@src') or [''])[0]
allitebooks.py:60: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if name is ('descr'):
Traceback (most recent call last):
  File "allitebooks.py", line 13, in <module>
    from lxml.html import fromstring
ModuleNotFoundError: No module named 'lxml'

C:\GitHub\allitebooks.com>

**Comment by themrinalsinha** [comment]
> C:\GitHub\allitebooks.com>python --version
> Python 3.8.2
> 
> C:\GitHub\allitebooks.com>python allitebooks.py
> allitebooks.py:56: SyntaxWarning: "is" with a literal. Did you mean "=="?
> if name is ('title'): return (header_details.xpath('./h1/text()') or [''])[0]
> allitebooks.py:57: SyntaxWarning: "is" with a literal. Did you mean "=="?
> if name is ('dlink'): return (book.xpath('//span[@Class="download-links"]/a[contains
> allitebooks.py:59: SyntaxWarning: "is" with a literal. Did you mean "=="?
> if name is ('cover'): return (header_details.xpath('.//div/a/img/@src') or [''])[0]
> allitebooks.py:60: SyntaxWarning: "is" with a literal. Did you mean "=="?
> if name is ('descr'):
> Traceback (most recent call last):
> File "allitebooks.py", line 13, in
> from lxml.html import fromstring
> ModuleNotFoundError: No module named 'lxml'
> 
> C:\GitHub\allitebooks.com>

Hey, fixed it also added requirements.txt
